### ISSUE TITLE
Why the shape of val_emb is (2, emb_dim)?

### ISSUE THREAD

**Issue by TimeLessLing** [sustcsonglin/second-order-neural-dmv#1]
Hi, I have read the code of NeuralDMV.py, but I have a question about the valence in NDMV.
In the NeuralDMV, I notice the shape of val_emb is (2, val_emb_dim), why the first dimension is 2?
As usual, the first dimension value of an embedding layer describe the number of types of the embedding object, eg. vocab_num for word embedding layer. So the `2` in the val_emb means only two types of valence in NDMV? Then what exactly are these two valence?

Thank you for your answer!

**Comment by sustcsonglin** [comment]
Yeah, there are two valence types: NOCHILD and HASCHILD. NOCHILD means that the parent word has not generated any  child words in the given direction and HASCHILD means that the parent word has generated child words in the given direction.
